Add a new login component
open-commercial/pos pull request #3
Opened 2023-09-09 22:21 UTC by facundososalopez

#1

2023-09-25 19:41 UTC, belluccifranco commented
![image](https://github.com/open-commercial/pos/assets/1295105/b1d67084-921c-4501-b8e7-310dd1b5b3fd)
- Expandir el rectangulo verde del fondo, a toda la pantalla
- Ante un error en el form, los input cambian de tamanio. Se deben mantener en un mismo tamanio
- Quitar el link de recuperar password

2023-09-25 19:50 UTC, belluccifranco commented on src/environments/environment.development.ts
Seguir la misma idea de nombres de archivos de ops-web: environment.ts y environment.production.ts

2023-09-25 19:51 UTC, belluccifranco commented on src/app/app-routing.module.ts
> +  { path: 'passwor-reset', title: MAIN_TITLE + " - Cambio de contraseña", component: PasswordResetComponent, canActivate: [publicGuard] },
Eliminar el routing de password reset

2023-09-25 19:55 UTC, belluccifranco requested changes
Revisar comentarios

2023-10-07 01:13 UTC, facundososalopez commented on src/environments/environment.development.ts
About enviroments, I just followed what's written here: https://angular.io/guide/build.
I remember you said that you wil fix the enviroments issue.

2023-10-08 12:51 UTC, belluccifranco approved these changes

2023-10-08 12:51 UTC, merged